// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/tvpbuilder/container.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	repository "github.com/equinor/radix-cost-allocation/pkg/repository"
	gomock "github.com/golang/mock/gomock"
)

// MockContainerBulkTvpBuilder is a mock of ContainerBulkTvpBuilder interface.
type MockContainerBulkTvpBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockContainerBulkTvpBuilderMockRecorder
}

// MockContainerBulkTvpBuilderMockRecorder is the mock recorder for MockContainerBulkTvpBuilder.
type MockContainerBulkTvpBuilderMockRecorder struct {
	mock *MockContainerBulkTvpBuilder
}

// NewMockContainerBulkTvpBuilder creates a new mock instance.
func NewMockContainerBulkTvpBuilder(ctrl *gomock.Controller) *MockContainerBulkTvpBuilder {
	mock := &MockContainerBulkTvpBuilder{ctrl: ctrl}
	mock.recorder = &MockContainerBulkTvpBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContainerBulkTvpBuilder) EXPECT() *MockContainerBulkTvpBuilderMockRecorder {
	return m.recorder
}

// Build mocks base method.
func (m *MockContainerBulkTvpBuilder) Build() ([]repository.ContainerBulkTvp, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Build")
	ret0, _ := ret[0].([]repository.ContainerBulkTvp)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Build indicates an expected call of Build.
func (mr *MockContainerBulkTvpBuilderMockRecorder) Build() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Build", reflect.TypeOf((*MockContainerBulkTvpBuilder)(nil).Build))
}
