apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: radix-cost-allocation
  annotations:
    github.com/project-slug: equinor/radix-cost-allocation
spec:
  type: other
  lifecycle: unknown
  owner: omnia-radix
