apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "cost-allocation.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "cost-allocation.labels" . | nindent 4 }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "cost-allocation.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cost-allocation.selectorLabels" . | nindent 8 }}
      {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccount: {{ include "cost-allocation.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: CRON_SCHEDULE
              value: {{ .Values.cronSchedule | quote }}
            - name: SCHEDULE_NODE_SYNC
              value: {{ .Values.schedule.nodeSync | quote }}
            - name: SCHEDULE_POD_SYNC
              value: {{ .Values.schedule.podSync | quote }}
            - name: SQL_DATABASE
              value: {{ .Values.db.database }}
            - name: SQL_SERVER
              value: {{ .Values.db.server }}
            - name: SQL_PORT
              value: {{ .Values.db.port | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
            - name: APP_NAME_EXCLUDE_LIST
              value: {{ .Values.appNameExcludeList }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
          {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
      {{- toYaml . | nindent 8 }}
      {{- end }}          

