apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "cost-allocation.fullname" . }}
  labels:
    {{- include "cost-allocation.labels" . | nindent 4 }}
rules:
- apiGroups:
  - radix.equinor.com
  resources:
  - radixregistrations
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ''
  resources:
  - pods
  - nodes
  - limitranges
  verbs:
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "cost-allocation.fullname" . }}
  labels:
    {{- include "cost-allocation.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "cost-allocation.fullname" . }}
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: {{ include "cost-allocation.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
