apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cost-allocation.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cost-allocation.labels" . | nindent 4 }}
