// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/repository/repository.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	repository "github.com/equinor/radix-cost-allocation/pkg/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// BulkUpsertContainers mocks base method.
func (m *MockRepository) BulkUpsertContainers(arg0 []repository.ContainerBulkDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertContainers", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpsertContainers indicates an expected call of BulkUpsertContainers.
func (mr *MockRepositoryMockRecorder) BulkUpsertContainers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertContainers", reflect.TypeOf((*MockRepository)(nil).BulkUpsertContainers), arg0)
}

// BulkUpsertNodes mocks base method.
func (m *MockRepository) BulkUpsertNodes(arg0 []repository.NodeBulkDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BulkUpsertNodes", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// BulkUpsertNodes indicates an expected call of BulkUpsertNodes.
func (mr *MockRepositoryMockRecorder) BulkUpsertNodes(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BulkUpsertNodes", reflect.TypeOf((*MockRepository)(nil).BulkUpsertNodes), arg0)
}
