# Default values for charts.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: radixdev.azurecr.io/radix-cost-allocation
  tag: latest
  pullPolicy: Always

job:
  schedule: "0 * * * *"
  restartPolicy: Never

secret:
  name: sql-credential

db:
  user: radixwriter
  database: sqldb-radix-cost-allocation
  server: sql-radix-cost-allocation-dev.database.windows.net
  password: password

prometheus:
  api: http://prometheus-operator-prometheus.default:9090