// Code generated by MockGen. DO NOT EDIT.
// Source: ./pkg/listers/nodebulkdto.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	repository "github.com/equinor/radix-cost-allocation/pkg/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeBulkDtoLister is a mock of NodeBulkDtoLister interface.
type MockNodeBulkDtoLister struct {
	ctrl     *gomock.Controller
	recorder *MockNodeBulkDtoListerMockRecorder
}

// MockNodeBulkDtoListerMockRecorder is the mock recorder for MockNodeBulkDtoLister.
type MockNodeBulkDtoListerMockRecorder struct {
	mock *MockNodeBulkDtoLister
}

// NewMockNodeBulkDtoLister creates a new mock instance.
func NewMockNodeBulkDtoLister(ctrl *gomock.Controller) *MockNodeBulkDtoLister {
	mock := &MockNodeBulkDtoLister{ctrl: ctrl}
	mock.recorder = &MockNodeBulkDtoListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeBulkDtoLister) EXPECT() *MockNodeBulkDtoListerMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockNodeBulkDtoLister) List() []repository.NodeBulkDto {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]repository.NodeBulkDto)
	return ret0
}

// List indicates an expected call of List.
func (mr *MockNodeBulkDtoListerMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNodeBulkDtoLister)(nil).List))
}
