name: radix-cost-allocation-build
on:
  push:
    branches:
      - master
      - release
permissions:
  id-token: write
jobs:
  build-deploy-image-dev:
    name: Build-push to dev
    env:
      IMAGE: radix-cost-allocation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Whitelist runner IP'
        run: |
          RUNNER_IP="$(curl --silent http://ifconfig.me/ip)"
          if [ -z "$(az acr network-rule list --name radixdev --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }} | grep ${RUNNER_IP})"]; then
            echo "Adding runner IP '${RUNNER_IP}' to Azure Container Registry 'radixdev' firewall whitelist"
            az acr network-rule add --name radixdev --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }} --ip-address $RUNNER_IP
          else
            echo "Runner is already whitelisted; skipping."
          fi
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: 'Build docker image'
        run: |
          docker build . -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - name: 'Login to dev'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - name: 'Push to dev'
        run: |
          az acr login --name radixdev --resource-group common
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - name: 'Blacklist runner IP'
        run: |
          RUNNER_IP="$(curl --silent http://ifconfig.me/ip)"
          echo "Adding runner IP '${RUNNER_IP}' to Azure Container Registry 'radixdev' firewall whitelist"
          az acr network-rule remove --name radixdev --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }} --ip-address $RUNNER_IP --only-show-errors --output none
  build-deploy-image-prod:
    if: github.ref == 'refs/heads/release'
    name: Build-push to prod
    env:
      IMAGE: radix-cost-allocation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Whitelist runner IP'
        run: |
          RUNNER_IP="$(curl --silent http://ifconfig.me/ip)"
          if [ -z "$(az acr network-rule list --name radixprod --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }} | grep ${RUNNER_IP})"]; then
            echo "Adding runner IP '${RUNNER_IP}' to Azure Container Registry 'radixprod' firewall whitelist"
            az acr network-rule add --name radixprod --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }} --ip-address $RUNNER_IP
          else
            echo "Runner is already whitelisted; skipping."
          fi
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: 'Build docker image'
        run: |
          docker build . -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - name: 'Login to prod'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_PROD }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }}
      - name: 'Push to prod'
        run: |
          az acr login --name radixprod --resource-group common
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
      - name: 'Blacklist runner IP'
        run: |
          RUNNER_IP="$(curl --silent http://ifconfig.me/ip)"
          echo "Adding runner IP '${RUNNER_IP}' to Azure Container Registry 'radixprod' firewall whitelist"
          az acr network-rule remove --name radixprod --resource-group common --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID_PROD }} --ip-address $RUNNER_IP --only-show-errors --output none
