name: Docker Image CI

on:
  push:
    branches: [master, release]

jobs:
  build-deploy-image-master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: radix-cost-allocation
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          docker build -t radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG -t radixprod.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
      - name: Azure login
        run: |
          az login --service-principal --username ${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.DEV_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radixdev
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          az logout
  build-deploy-image-release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: radix-cost-allocation
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image dev
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          docker build -t radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
      - name: Azure login dev
        run: |
          az login --service-principal --username ${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.DEV_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radix dev
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          az logout
            - uses: actions/checkout@v2
      - name: Build Docker image prod
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          docker build -t radixprod.azurecr.io/$IMAGE_NAME:$IMAGE_TAG .
      - name: Azure login prod
        run: |
          az login --service-principal --username ${{secrets.PROD_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.PROD_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.PROD_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radix prod
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          az acr login -n radixprod -g common
          docker push radixprod.azurecr.io/$IMAGE_NAME:$IMAGE_TAG
          az logout