name: Deploy ARM to dev

on:
  push:
    branches: [master]

jobs:
  deploy-sql-server:
    runs-on: ubuntu-latest
    env:
      RESOURCE_GROUP: cost-allocation
      KEY_VAULT_NAME: radix-vault-dev
      SQL_SERVER_NAME: sql-radix-cost-allocation-dev
      DB_NAME: sqldb-radix-cost-allocation
      DB_USER_NAME: radix
      FIREWALL_RULE_NAME: githubRunnerIp
      ADMIN_GROUP_NAME: 'Radix Platform Developers'
      ADMIN_GROUP_ID: "a5dfa635-dc00-4a28-9ad9-9e7f1e56919d"
      SQL_LOG_STORAGE_NAME: radixsqllogsdev
    steps:       
      - uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID_DEV }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID_DEV }}
      - uses: Azure/get-keyvault-secrets@v1
        with:
          keyvault: ${{ env.KEY_VAULT_NAME }}
          secrets: "radix-cost-allocation-db-admin"
        id: adminPassword
      - name: Deploy SQL Server and DB
        env:
          DEPLOY_NAME: radix-cost-db-deploy
        run: |

          # Get Storage Account ID for sql logs
          storageId=$(az storage account show --name "$SQL_LOG_STORAGE_NAME" --query "id" --output tsv)        

          az deployment group create -g "$RESOURCE_GROUP" -n "$DEPLOY_NAME" \
            --template-file ./azure-infrastructure/azuredeploy.json \
            --parameters sqlServerName="$SQL_SERVER_NAME" \
            --parameters databaseName="$DB_NAME" \
            --parameters sqlAdministratorLoginPassword="${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}" \
            --parameters sqlAdministratorLoginUser="$DB_USER_NAME" \
            --parameters adminGroupName="$ADMIN_GROUP_NAME" \
            --parameters adminGroupId="$ADMIN_GROUP_ID" \
            --parameters storageAccountId=$storageId

      - name: Whitelist Runner IP in firewalls
        shell: pwsh
        run: |
          $runnerIp = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
          az sql server firewall-rule create `
            --end-ip-address $runnerIp `
            --start-ip-address $runnerIp `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}
      - name: Creating DB schema and tables
        shell: pwsh
        run: |
          Set-PSRepository -Name "PSGallery" -InstallationPolicy Trusted
          Install-Module -Name SqlServer

          $targetSqlServerFQDN = "$(az sql server show -n ${env:SQL_SERVER_NAME} -g ${env:RESOURCE_GROUP} | jq -r .fullyQualifiedDomainName)"

          Invoke-Sqlcmd -InputFile ./azure-infrastructure/preDeployScript.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
          Invoke-Sqlcmd -InputFile ./azure-infrastructure/createSchema.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
          Invoke-Sqlcmd -InputFile ./azure-infrastructure/createTables.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
          Invoke-Sqlcmd -InputFile ./azure-infrastructure/createTypes.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
          Invoke-Sqlcmd -InputFile ./azure-infrastructure/createViews.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
          Invoke-Sqlcmd -InputFile ./azure-infrastructure/createProcedures.sql -ServerInstance $targetSqlServerFQDN -Database ${env:DB_NAME} -Username ${env:DB_USER_NAME} -password ${{ steps.adminPassword.outputs.radix-cost-allocation-db-admin }}
      - name: Blacklist Runner IP in firewalls
        shell: pwsh
        if: ${{ always() }}
        run: |
          $runnerIp = (Invoke-WebRequest -uri "http://ifconfig.me/ip").Content
          az sql server firewall-rule delete `
            --name ${env:FIREWALL_RULE_NAME} `
            --resource-group ${env:RESOURCE_GROUP} `
            --server ${env:SQL_SERVER_NAME}
