name: Docker Image CI

on:
  push:
    branches: [master, release]

jobs:
  build-deploy-image-master:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    env:
      IMAGE: radix-cost-allocation
    steps:
      - uses: actions/checkout@v2
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: Build Docker image
        run: |
          docker build -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} .
      - name: Azure login
        run: |
          az login --service-principal --username ${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.DEV_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radixdev
        run: |
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          az logout
  build-deploy-image-release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    env:
      IMAGE: radix-cost-allocation
    steps:
      - uses: actions/checkout@v2
      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"
      - name: Build Docker image dev
        run: |
          docker build -t radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} .
      - name: Azure login dev
        run: |
          az login --service-principal --username ${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.DEV_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.DEV_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radix dev
        run: |
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          az logout
      - name: Build Docker image prod
        run: |
          docker build -t radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }} .
      - name: Azure login prod
        run: |
          az login --service-principal --username ${{secrets.PROD_AZURE_CREDENTIALS_CLIENT_ID}}  --password "${{secrets.PROD_AZURE_CREDENTIALS_CLIENT_SECRET}}" --tenant ${{secrets.AZURE_TENANT_ID}}
          az account set -s "${{secrets.PROD_AZURE_SUBSCRIPTION_ID}}"
      - name: Push to radix prod
        run: |
          az acr login -n radixprod -g common
          docker push radixprod.azurecr.io/${{ env.IMAGE }}:${{ steps.prep.outputs.BUILD_ID }}
          az logout
