name: Docker Image CI

on:
  push:
    branches: [master, release, feature/pushacr]

jobs:
  build-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          docker build -t radixdev.azurecr.io/radix-cost-exporter:$IMAGE_TAG -t radixprod.azurecr.io/radix-cost-exporter:$IMAGE_TAG .
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Push to radixdev
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          az acr login -n radixdev -g common
          docker push radixdev.azurecr.io/radix-cost-exporter:$IMAGE_TAG
          az logout
      - uses: Azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      - name: Push to radixprod
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}-${{ github.sha }}
          az acr login -n radixprod -g common
          docker push radixprod.azurecr.io/radix-cost-exporter:$IMAGE_TAG