name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:
  build-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t radixdev.azurecr.io/radix-cost-exporter:${GITHUB_REF##*/}-${{ github.sha }} .
      - uses: azure/docker-login@v1
        with:
          login-server: radixdev.azurecr.io
          username: ${{ secrets.DEV_REGISTRY_USERNAME }}
          password: ${{ secrets.DEV_REGISTRY_PASSWORD }}
      - name: push to radixdev
        run: |
          docker push radixdev.azurecr.io/radix-cost-exporter:${GITHUB_REF##*/}-${{ github.sha }}
  deploy-db-arm-template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: deploy-arm-template
        env:
          DEPLOY_NAME: radix-cost-db-deploy
        run: |
          BRANCH=${GITHUB_REF##*/} 
          RESOURCE_GROUP=common
          
          az deployment group create -g $RESOURCE_GROUP -n $DEPLOY_NAME \
            --template-file ./azure-infrastructure/azuredeploy.json \
            --parameters ./azure-infrastructure/azuredeploy.parameters.json \
            --parameters sqlAdministratorLoginPassword=${{ secrets.DB_PASSWORD }}