name: radix-cost-allocation-pr
on:
  pull_request:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      env:
        REF: ${{ github. sha }}
      run: docker build -t radix-cost-allocatation:${REF##*/} .
  